# Generated by Django 5.1 on 2024-08-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yabbyapp', '0002_note_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='notes_pdfs/'),
        ),
    ]
