# Generated by Django 5.1 on 2024-09-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yabbyapp', '0003_note_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/previews/'),
        ),
    ]
