# Generated by Django 5.1 on 2024-09-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yabbyapp', '0006_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='grade_level',
            field=models.CharField(choices=[('seconde', 'Seconde'), ('bac_general', 'Bac Général'), ('bac_tech', 'Bac Technologique')], default='seconde', max_length=20),
        ),
    ]
