# Generated by Django 5.1 on 2024-09-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yabbyapp', '0007_note_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='section',
            field=models.CharField(choices=[('Seconde', 'Seconde'), ('Bac Général', 'Bac Général')], default='Seconde', max_length=20),
            preserve_default=False,
        ),
    ]
