# Generated by Django 5.1 on 2024-09-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yabbyapp', '0008_note_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='section',
            field=models.CharField(choices=[('Seconde', 'Seconde'), ('Bac Général', 'Bac Général'), ('Bac Technologique', 'Bac Technologique')], max_length=20),
        ),
    ]
